import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AdminLayout from "@/components/Common/AdminLayout";
import Sidebar from "@/components/Common/Sidebar";
import Header from "@/components/Common/Header";
import LoginPage from "@/components/Login";
import { UserProvider } from "@/Context/UserContext";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       {/* <AdminLayout> */}
       {/* <Head children={undefined}/>
        */}
        <head></head>
       {/* <Header/>
       <Sidebar/> */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <LoginPage/> */}
        {/* <UserProvider> */}
        {children}
        {/* </UserProvider> */}
        {/* <Sidebar/> */}
        
      </body>
      {/* </AdminLayout> */}
    </html>
  );
}
